# Generated by Django 2.2.1 on 2019-05-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestInfoTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='RssDataTbl',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
                ('article', models.CharField(max_length=2000)),
            ],
        ),
    ]
