# Generated by Django 2.2.1 on 2019-05-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestinfotbl',
            name='pubDate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rssdatatbl',
            name='pubDate',
            field=models.CharField(max_length=200),
        ),
    ]
